name: Check

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install deps
        run: yarn
      - name: Build
        run: yarn build
